default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: private_results_development

test:
  <<: *default
  database: private_results_test

production:
  adapter: postgresql
  database: private_results_production
  encoding: unicode
  host: db
  password:
  pool: 5
  username: postgres
